### ISSUE TITLE
Some data not synchronised between works and images APIs

### ISSUE THREAD

**Issue by davidpmccormick** [wellcomecollection/platform#6195]
We were notified that there's a journey that isn't working for certain images on wellcomecollection.org ([Slack thread](https://wellcome.slack.com/archives/C8X9YKM5X/p1762429996981809))

The root cause appears to be that the image associated with some works e.g. `px2pthe6` (image ID: `wp7ge5pt`) have not been indexed in the images search API. If you [query the images API directly for this image ID](https://api.wellcomecollection.org/catalogue/v2/images/wp7ge5pt) it returns a 404.

**Comment by pollecuttn** [comment]
Another example here:
https://wellcomecollection.org/works/bzxx9ze3 
Slack: https://wellcome.slack.com/archives/C8X9YKM5X/p1759764188780389

**Comment by jcateswellcome** [comment]
We should investigate how widespread this issue is, in case there are many unreported cases of this.

**Comment by paul-butcher** [comment]
There were four messages in the image inferrer dlq, none of which referred to either of the missing images mentioned above (redriven anyway).
Injecting the Work identifiers back into the pipeline also did not help. This implies that it is not some ephemeral issue.

It also seems to be far too common to ignore.
Out of a sample of 10,000 Image ids mentioned in Works, I found 84 missing images.

 ['a323rayk', 'a4vgh7zw', 'a659duyh', 'a6xd28gq', 'a828yddp', 'a8x4taz4', 'a9n6ybf4', 'aa9nb9se', 'aaj6ng4b', 'abe9hed3', 'ac5j5944', 'acgvdhvn', 'acq7ert5', 'aehwwr29', 'af59w76d', 'afarrckf', 'age7jsw7', 'agmp9h7t', 'agsvz7ns', 'agy72d8p', 'agz5sfvp', 'aje8cgyn', 'anh3wmb5', 'apb9auyw', 'ar6u6jnv', 'at8e5qsy', 'avbqxjp9', 'aww6tqjz', 'axzeqtqu', 'ay9n2hng', 'ay9sbf6j', 'aywm2swp', 'b25nmv8u', 'b28e4nab', 'b3czghc2', 'b63d9pww', 'b7376kud', 'b7kemre7', 'b7sr3xxh', 'b7yktjy9', 'bajvn6fy', 'bb5gjdeb', 'bbwwfypn', 'bbysv44y', 'bc84a2jz', 'bcwzfn5z', 'bdpatpu5', 'bdryzpdh', 'bds9vkuc', 'beacy7yq', 'bevt4642', 'bffwv9re', 'bgxmhmxq', 'bkng6pgz', 'bp63t798', 'bqabm6py', 'bqjct7gc', 'bqyggd7q', 'br3q2hds', 'br9ps2js', 'bu9z4qct', 'bvbpg5yw', 'bwfs9bwe', 'bwgnutr6', 'bxm33z4k', 'bzsga8db', 'bzsh3kxw', 'c3tppzn9', 'c3tx4u8k', 'c3ym7v3g', 'c43a3m6w', 'c47ugtxx', 'c4hgrh5w', 'c69nrkp8', 'c6g422w2', 'c6jru3xh', 'c7esudgw', 'c8dxy45h', 'c8f3m9v5', 'c8j9jhts', 'c9ppx65h', 'cd683z33', 'cdxynwcg', 'cey4nnep', 'cfmrff56', 'cfudgtbm']

**Comment by paul-butcher** [comment]
I've had a look at a few of these, and all the ones I looked at were digmiro.  However, none of the ones I looked at had a corresponding mets.

e.g. looking at this missing image - c4hgrh5w 

`GET _search/?q=c4hgrh5w`
returns  an indexed work (sourced from Miro) [bj9pbwvm - D. Hanbury, 'On some rare kinds of cardamon'
](https://wellcomecollection.org/works/bj9pbwvm), which has the following data
```
"identifiers.value": [
              "L0013185",
              "b13531311"
            ],
            "images.id": [
              "c4hgrh5w"
            ],
            "images.identifiers.value": [
              "L0013185"
            ],
```

Only those two exist in the merge graph - https://main.d33vyuqnhij7au.amplifyapp.com/?workId=bj9pbwvm

Looking in works-source for b13531311 yields 6 records. One of which is Work[sierra-system-number/b13531311], "The pharmaceutical journal and transactions.", the remaining 5 are Miro images.  L0013185 and L0013184, which both appear to be pertinent to Hanbury's Cardamom, but the others are "Draft diploma of the Pharmaceutical Society of London." "Heineken ether-inhalation apparatus." and "Robbery by means of chloroform".

**Comment by paul-butcher** [comment]
Oho! This is interesting.  There are no digmiro records in indexed with a populated images.id field.  So the records that are digmiro upstream of the merger are not being considered properly downstream of it.

```
{
    "size":0,
          "query": {
              "terms": {
                  "query.identifiers.value": ["digaids", "digmiro"]
              }
          },
          "aggs": {
              "images": {
                  "terms": {"size": 10000, "field": "query.images.id"}
              }
          }
}```

**Comment by paul-butcher** [comment]
Compare this to a correctly processed digaids record: https://wellcomecollection.org/works/muwybztv

This consists of a METS work: [d2xvhvkk](https://wellcomecollection.org/works/d2xvhvkk) (mets/b16722838), redirected to [muwybztv](https://wellcomecollection.org/works/muwybztv) (Sierra/b16722838), and an image: [pup5p3hz](https://wellcomecollection.org/works/muwybztv/images?id=pup5p3hz)(mets/b16722838)

Searching for b16722838 in source gives three results - a [Miro](https://wellcomecollection.org/works/pazd5d9p)(L0053097), a Mets and a Sierra. (as expected).  pazd5d9p also redirects to muwybztv.

**Comment by paul-butcher** [comment]
There appears to be no mets record for b13531311

**Comment by paul-butcher** [comment]
Candidate causes might be:

* Something is awry in Sierra or the transformer, marking a record as digmiro when it isn't.
* Some mets records have vanished
* Something is awry in Sierra, the transformer, or the matcher/merger, linking a Miro record to the wrong Sierra record.
* Something awry in the matcher/merger, it is failing to merge and redirect these records.

**Comment by paul-butcher** [comment]
Another notable feature is that the corresponding b number for all the records I've looked at so far seems to correspond to a relatively large number of records in works-identified

For example: 
* c8f3m9v5 (one of the missing images) is part of [shxeaz5b](https://wellcomecollection.org/works/shxeaz5b) (a Work with an image link that goes to 404)
* in works-indexed, shxeaz5b contains the ids sierra:b16576111 and miro:L0055233
* works identified: _search?q=b16576111 yields 45 records.  One of which is gfnjjktm, which redirects to gaqf2ffu, as does zmmbjkja
* zmmbjkja has shxeaz5b/L0055233 as a merge candidate (amongst others)

I wonder if the matcher is not returning all the matches - e.g. because the request has a limit on the number of records it can return?

**Comment by paul-butcher** [comment]
Of the ids in the zmmbjka matcher subgraph, only one (gfnjjktm) corresponds to a redirected work:
[
"f8hev3uu" ,
"fcwzu9xa" ,
"fwwhkv67" ,
"g3xwqdbv" ,
"gaqf2ffu" ,
"gfnjjktm" ,
"mxgq8gmj" ,
"qtejsuc5" ,
"shxeaz5b" ,
"tva247uv" ,
"x5nk6ah7" ,
"zmmbjkja" 
 ]

gaqf2ffu is the METS work.  Even zmmbjkja itself is not redirected

**Comment by paul-butcher** [comment]
Some of the Sierra records in https://main.d33vyuqnhij7au.amplifyapp.com/?workId=gfnjjktm appear to have been deleted when viewed on the website

e.g. https://wellcomecollection.org/works/ckehh622 ~~If these are merged, then I would expect them to be redirected, rather than deleted.~~ I think that's a bit of a red herring.

**Comment by paul-butcher** [comment]
The problem is to do with merge rules and the fact that the Sierra record refers to a book.

Two things can happen to a Work derived from Miro record.
1. It redirects to a Sierra record
    1.  It gets merged into the Sierra record, the Sierra record then contains the images in imagedata, 
    2. It gets discarded - this happens when it has been overridden by a METS record - (digmiro)
2. It continues to exist in its own right.  Standalone image records are created.

The trouble is that the above decisions are independent, and (in the case of this bug) do not necessarily add up to 100%.

The merger outcome consists of a list of works (all unredirected works from the merge) and a list of standalone images (any records that need to go through the images pipeline).

For a work to be redirected, it must contribute to 

There are various routes for a Miro record to be merged into a Sierra record, (and thus be redirected 1.i, above), but the common condition is that the Sierra work must have zero or one items.  In the case of a digmiro Work, the Miro image data is ignored, but it will still be added to the otheridentifiers list and be redirected.

For a Miro record to continue in its own right, the Sierra record involved in the merge cannot be digmiro.

So the truth table for this has a bit of a hole:

|     multiple items  | digmiro | result|
| --- | --- | --- | 
| N  | N | merge |
| Y|N|standalone|
|N|Y| discard |
|Y|Y|!?Oh No?!|

In the "Oh No!" case, the Work derived from Miro persists as a Work with a list of image references, but the images are not emitted to go through the images pipeline.  The result being these missing links.  This is because it was ineligible to be included in a merge (so the work continues), but also ineligible to create a standalone image.

**Comment by paul-butcher** [comment]
So the result of the gaqf2ffu merge is this:

- main record: id=gaqf2ffu - Work[sierra-system-number/b33581277]
- redirected: [(id=gfnjjktm - Work[mets/b16576111]),(id=zmmbjkja - Work[sierra-system-number/b16576111])] 
- remaining records: [(id=qtejsuc5 - Work[miro-image-number/L0055236]),(id=fwwhkv67 - Work[miro-image-number/L0055232]),(id=shxeaz5b - Work[miro-image-number/L0055233]),(id=g3xwqdbv - Work[miro-image-number/L0055231]),(id=fcwzu9xa - Work[miro-image-number/L0055230]),(id=mxgq8gmj - Work[miro-image-number/L0055235]),(id=f8hev3uu - Work[miro-image-number/L0055237]),(id=x5nk6ah7 - Work[miro-image-number/L0055238]),(id=tva247uv - Work[miro-image-number/L0023188])]

The target when considering images is zmmbjkja (first preference for image merging is a sierraDigitisedMiro, regardless of the main target)

What is happening here, is that when we try to merge the images into zmmbjkja/b16576111 (which has no items of its own) the images are ignored, and then not emitted because it is a digmiro record.  But when we try to merge the micro _works_ (e.g. into otherIdentifiers), they are being merged into gaqf2ffu - Work[sierra-system-number/b33581277], which has multiple items, so they are being ignored for that reason.

**Comment by paul-butcher** [comment]
Regardless of which Sierra record is used as the target, they would also not be included in otherIdentifiers because both zmmbjkja/b16576111 and gaqf2ffu /b33581277 are Books (not picture or 3d object), and cannot act as recipients for Miro ids.

This also causes a slightly less conspicuous problem for the one mets record in the merge gfnjjktm.

Looking at a correctly behaving digmiro (the AIDS poster, above), we can search for the id in images:https://wellcomecollection.org/search?query=pup5p3hz and get a result.  No such luck for when the digmiro is a book: https://wellcomecollection.org/search/images?query=gfnjjktm

**Comment by paul-butcher** [comment]
[e52vpkpb](https://wellcomecollection.org/works/e52vpkpb) is notable, as it is digmiro, but no METS record appears in the merge. [h8u4tgjx](https://wellcomecollection.org/works/h8u4tgjx) is one of the Miro records that it matches with.

**Comment by pollecuttn** [comment]
Blocked waiting for feedback from Georgia

**Comment by georgiaewhitney** [comment]
Apologies for the delay - am discussing this with Branwen.

**Comment by paul-butcher** [comment]
Having had a conversation with Christy, it looks like the right answer is that digmiro should ALWAYS suppress the Miro, regardless of number of items or type of work.

**Comment by paul-butcher** [comment]
In the case of [e52vpkpb](https://wellcomecollection.org/works/e52vpkpb) where no METS record appears in the merge.  This is expected, as the actual images are associated with the CALM records linked in the description.  The Miro Images linked to are therefore duplicates and should not exist.

**Comment by paul-butcher** [comment]
So, in the case of the work that started it all - px2pthe6 - that Work should simply not exist (redirect to [mtctkh4b](https://wellcomecollection.org/works/mtctkh4b))

**Comment by pollecuttn** [comment]
@paul-butcher as far as I can see the original problem re px2pthe6 as reported via the Slack link when this issue was opened hasn't changed. Have I jumped the gun or should it be resolved now?

**Comment by paul-butcher** [comment]
My mistake, I hadn't tagged it as awaiting reindex.  The code is complete and merged, but those records still need to go through the pipeline

**Comment by pollecuttn** [comment]
Hi @paul-butcher neither of the two linked Slack messages seem to be resolved. Is there something else that needs to happen following the reindex for the images to appear?

**Comment by paul-butcher** [comment]
This is now behaving correctly as designed.  The original problem was a disconnect between one thing saying there is an image, and then there not being an image.   It is now the case that digmiro is always respected, so the disconnect no longer occurs.

However, I think there is still an issue to consider around M-Series images.  These are being (I think, correctly) associated with digmiro Sierra records, but they are not present in the corresponding METS content.

I think we need to do a bit more analysis and have a discussion with digitisation folk to come up with a solution that allows more recently digitised images to be visible alongside the formerly digitised L-Series images now coming from METS (if that is desirable)
